### PR TITLE
All cursors and custom overtype cursor

### PR DESCRIPTION
**Pull request by DrMerfy**
- Fixed issue #11 by supporting all available cursors.
- Added a configuration setting for custom overtype support:
`"overtype.secondaryCursorStyle": "line" | "line-thin" | "block" | "block-outline" | "underline" | "underline-thin`
This setting changes the cursor style when overtype mode is selected.
- The minimum vscode engine version is now 1.10.0 (due to new cursor addition)

### CODE REVIEW

**Comment by ssmooncoder** [comment]
Is this extension dead?

This branch should have been merged years ago…

**Comment by DrMerfy** [comment]
@ssmooncoder It sure looks like it.

image

**Comment by GitMensch** [comment]
@DrMerfy would you take on the maintenance for this extension?

* enable issues on your fork
* pull in #18
* adjust package.json - publisher and urls
* adjust README
* _maybe_ handle some of the other issues
* release as 0.3.0 (in this case please not only to vscode marketplace but also to [Open VSX Registry](https://open-vsx.org/?search=overtype)

That would be awesome!

Side note: Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions you may publish this extension with a single command, `npx ovsx publish` (no need to install any dependency)

**Comment by DrMerfy** [comment]
@GitMensch Mhm okay I'll take a look in the upcoming days. Let's bring it back to life :D

**Comment by DrMerfy** [comment]
Okay I have made all the necessary changes, you can find them also here: https://github.com/DrMerfy/vscode-overtype

(But also on the references above :) )

**Comment by GitMensch** [comment]
@DrMerfy can you close this PR? That's more than this PR was about...

**Comment by DrMerfy** [comment]
@GitMensch True true

**Pull request closed without merging**
